services:

  backend: 
    container_name: tgc-backend
    build: ./backend
    volumes:
      - ./backend/src/:/app/src/
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}

  frontend:
    container_name: tgc-frontend
    build: ./frontend
    volumes:
      - ./frontend/src/:/app/src/
    environment:
      VITE_GATEWAY_PORT: ${GATEWAY_PORT}
  
  database:
    container_name: tgc-database
    image: postgres
    volumes:
      - ./persist/data/:/var/lib/postgresql/data
    environment:
    # /!\ Environment syntax: https://stackoverflow.com/questions/60200966/docker-compose-gives-invalid-environment-type-error
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
      # - DB_HOST=${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}

  visualizer:
    container_name: tgc-visualizer
    image: adminer

  gateway:
    container_name: tgc-gateway
    image: nginx
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf